apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-helloworld
  name: python-helloworld-deployment
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: python-helloworld
  strategy: {}
  template:
    metadata:
      labels:
        app: python-helloworld
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: python-helloworld
