apiVersion: v1
kind: Service
metadata:
   name: python-helloworld-service
   labels:
     app: python-helloworld
spec:
  type: NodePort
  ports:
          - port: 80
            nodePort: {{ .Values.service.nodeport }}
            targetPort: {{ .Values.service.targetport }}

  selector:
    app: python-helloworld       
