apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-helloworld
  name: python-helloworld-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-helloworld
  strategy: {}
  template:
    metadata:
      labels:
        app: python-helloworld
    spec:
      containers:
      - image: ksaurabh/python-helloworld
        name: python-helloworld

