apiVersion: v1
kind: Service
metadata:
  name: pyhton-helloworld-service
  labels:
    app: python-helloworld
spec:
 type: NodePort
 ports:
   - port: 80
     targetPort: 5000  
     nodePort: 30010
 selector:
   app: python-helloworld

